### PR TITLE
constrain regex matching in reference replacement

### LINKED ISSUE #11: Incorrect reference resolved
Hey, i noticed that sometimes references get resolved incorrectly.
```
Bar:
  bar1:
    title: {{name.findName}}

FooBar:
  foobar1:
    title: {{name.findName}}

Baz:
  baz1:
    title: {{name.findName}}
    bar: @bar1 // references "@foobar1" instead.
```

PS Lmk if you need further help to reproduce this. Great library anyway!

### PR DESCRIPTION
**Pull request by aaronbuchanan**
This fixes #11 by limiting the matches to the regex when looking up responses.

I wasn't sure the best way to construct a test for this due to randomness in the matching, but I did verify this didn't break any existing tests. @sghribi lmk if you have thoughts there.

Cheers, thanks for the lib, btw!

### CODE REVIEW

File: src/load-fixtures.coffee [hunk 1]
```diff
@@ -1,5 +1,5 @@
-`#!/usr/bin/env node
-`
```
Comment (sghribi) [inline src/load-fixtures.coffee]: @aaronbuchanan : I've added these backquotes in order to keep the shebang line after coffee->js compilation

Could you remove this from your PR please ?

**Review by sghribi — CHANGES_REQUESTED** [review]

**Review by sghribi — APPROVED** [review]
